# Generated by Django 3.2.5 on 2022-03-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_predication_old_peak'),
        ('api', '0002_alter_predication_user'),
    ]

    operations = [
    ]
